::OPEN_GROUP
[SOURCE OPEN]
groups.txt
[SOURCE /OPEN]
[SOURCE GET]
[SYSTEM RUN],www.google.com,[ENTER/],[WAIT 1000]
[CONTROL],t,[/CONTROL],[WAIT 100]
[CONTROL],v,[/CONTROL]
::OPEN_GROUP
::OPEN_POST
[SOURCE OPEN]
post.txt
[SOURCE /OPEN]
[SOURCE GET]
[SYSTEM RUN]
[CONTROL],v,[/CONTROL],[ENTER/],[WAIT 2000]
::OPEN_POST
::CLOSE_POST
[CONTROL],w,[/CONTROL],[WAIT 600],[ENTER/]
::CLOSE_POST
[WAIT 530],[CONTROL],a,[/CONTROL]
[CONTROL],x,[/CONTROL],[WAIT 900]
::RESTART_POST
[CONTROL],[SHIFT],t,[/SHIFT],[/CONTROL],[WAIT 656]
::RESTART_POST
::MODE_GROUP
[WAIT 1000]
[SHIFT],[TAB/],[/SHIFT]
[DOWN/],[WAIT 499]
[DOWN/],[WAIT 450]
[DOWN/],[WAIT 600]
[ENTER/]
::MODE_GROUP
::SELECT_GROUP
[WAIT 1340],[CONTROL],v,[/CONTROL],[WAIT 1150],[DOWN/],[WAIT 1050],[ENTER/],[WAIT 1234]
::SELECT_GROUP
::POST
[WAIT 4321],
[CONTROL],f,[/CONTROL],post::123,[ENTER/],[WAIT 21],[ESCAPE/],[WAIT 32],[ENTER/]
::POST